CREATE TABLE form_data (
	id INT PRIMARY KEY AUTO_INCREMENT,
	
	nombrePA VARCHAR(100),
	tipoRegistro VARCHAR(100),
	descripcion TEXT,
	areaResponsable VARCHAR(50),
	cargoResponsable VARCHAR(100),
	tipoInicio VARCHAR(100),
	actoInicio VARCHAR(200),
	actoTermino VARCHAR(200),
	prodInstitucional VARCHAR(200),
	
	numLey VARCHAR(20),
	urlLey VARCHAR(200),
	fuentesNorm VARCHAR(10),
	tipoFuente VARCHAR(200),
	nombreFuente VARCHAR(200),
	urlFuente VARCHAR(200),
	
	pago VARCHAR(50),
	tipoMoneda VARCHAR(200),
	monto VARCHAR(20),
	tipoUsuario VARCHAR(200),
	segmentoUsuarios VARCHAR(200),
	disponibilidad VARCHAR(200),
	rsh VARCHAR(200),
	
	nivelDig VARCHAR(200),
	fechaDig VARCHAR(200),
	tipoExp VARCHAR(200),
	accesoExp VARCHAR(200),
	urlInicio VARCHAR(200),
	chileAtiende VARCHAR(10),
	urlChileAtiende VARCHAR(200),
	numPlataformas VARCHAR(10),
	alcancePlataformas VARCHAR(200),
	canalAtencionDigital BOOLEAN,
	canalAtencionPresencial BOOLEAN,
	canalAtencionTelefonico BOOLEAN,
	canalAtencionAuto BOOLEAN,
	canalTransDigital BOOLEAN,
	canalTransPresencial BOOLEAN,
	canalTransTelefonico BOOLEAN,
	canalTransAuto BOOLEAN,
	platSimpleSaas BOOLEAN,
	platSimpleOnPremise BOOLEAN,
	platPropio BOOLEAN,
	platEstado BOOLEAN,

	autenticacionUsuario VARCHAR(200),
	autenticacionFuncionario VARCHAR(200),
	firmaElec VARCHAR(200),
	
	notificaciones VARCHAR(10),
	notifInicio VARCHAR(200),
	notifInstruc VARCHAR(200),
	notifTermino VARCHAR(200),
	comInstitucionales VARCHAR(200),
	comPersonales VARCHAR(200),
	etapaNotifInicio BOOLEAN,
	etapaNotifInstruc BOOLEAN,
	etapaNotifTermino BOOLEAN,
	
	docsOrganos VARCHAR(10),
	mediosOrganos VARCHAR(200),
	institucionProveedora VARCHAR(200),
	medioInterop VARCHAR(200),
	servicioWeb VARCHAR(200),
	docNotarial VARCHAR(10),
	nombreDocNotarial VARCHAR(200),
	medioComOficial VARCHAR(200)
)