import sequelize from "../config/db.js";
import { DataTypes } from "sequelize";

const FormData = sequelize.define('form_data', {
    id: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true
    },
    nombrePA: DataTypes.STRING,
    tipoRegistro: DataTypes.STRING,
    descripcion: DataTypes.STRING,
    areaResponsable: DataTypes.STRING,
    cargoResponsable: DataTypes.STRING,
    tipoInicio: DataTypes.STRING,
    actoInicio: DataTypes.STRING,
    actoTermino: DataTypes.STRING,
    prodInstitucional: DataTypes.STRING,
    numLey: DataTypes.STRING,
    urlLey: DataTypes.STRING,
    fuentesNorm: DataTypes.STRING,
    tipoFuente: DataTypes.STRING,
    nombreFuente: DataTypes.STRING,
    urlFuente: DataTypes.STRING,
    pago: DataTypes.STRING,
    tipoMoneda: DataTypes.STRING,
    monto: DataTypes.STRING,
    tipoUsuario: DataTypes.STRING,
    segmentoUsuarios: DataTypes.STRING,
    disponibilidad: DataTypes.STRING,
    rsh: DataTypes.STRING,
    nivelDig: DataTypes.STRING,
    fechaDig: DataTypes.STRING,
    tipoExp: DataTypes.STRING,
    accesoExp: DataTypes.STRING,
    urlInicio: DataTypes.STRING,
    chileAtiende: DataTypes.STRING,
    urlChileAtiende: DataTypes.STRING,
    numPlataformas: DataTypes.STRING,
    alcancePlataformas: DataTypes.STRING,
    canalAtencionDigital: DataTypes.BOOLEAN,
    canalAtencionPresencial: DataTypes.BOOLEAN,
    canalAtencionTelefonico: DataTypes.BOOLEAN,
    canalAtencionAuto: DataTypes.BOOLEAN,
    canalTransDigital: DataTypes.BOOLEAN,
    canalTransPresencial: DataTypes.BOOLEAN,
    canalTransTelefonico: DataTypes.BOOLEAN,
    canalTransAuto: DataTypes.BOOLEAN,
    platSimpleSaas: DataTypes.BOOLEAN,
    platSimpleOnPremise: DataTypes.BOOLEAN,
    platPropio: DataTypes.BOOLEAN,
    platEstado: DataTypes.BOOLEAN,
    autenticacionUsuario: DataTypes.STRING,
    autenticacionFuncionario: DataTypes.STRING,
    firmaElec: DataTypes.STRING,
    notificaciones: DataTypes.STRING,
    notifInicio: DataTypes.STRING,
    notifInstruc: DataTypes.STRING,
    notifTermino: DataTypes.STRING,
    comInstitucionales: DataTypes.STRING,
    comPersonales: DataTypes.STRING,
    etapaNotifInicio: DataTypes.BOOLEAN,
    etapaNotifInstruc: DataTypes.BOOLEAN,
    etapaNotifTermino: DataTypes.BOOLEAN,
    docsOrganos: DataTypes.STRING,
    mediosOrganos: DataTypes.STRING,
    InstitucionProveedora: DataTypes.STRING,
    medioInterop: DataTypes.STRING,
    servicioWeb: DataTypes.STRING,
    docNotarial: DataTypes.STRING,
    nombreDocNotarial: DataTypes.STRING,
    medioComOficial: DataTypes.STRING,
    marcado: DataTypes.BOOLEAN,
}, { timestamps: false })

export default FormData